# -*- makefile-gmake -*-

.PHONY: ledit announce version configure

# Check if the "ledit" library is present.
ledit:
	@ echo 'include Ledit;;' | ocaml | grep Error > /dev/null 2> /dev/null
	@ if test "$?" = "0" ; then 									\
	  echo ' * Ledit is present: use it as UserInput.';				\
	  echo 'let use_ledit = true' > myocamlbuild_config.ml ;		\
	else															\
	  echo 'include StdUserInput' > src/utilities/userInput.ml;		\
	  echo ' * Ledit is not present: use default UserInput.';		\
	  echo 'let use_ledit = false' > myocamlbuild_config.ml ;		\
	fi

version:
	@ echo "let number = \"$(VERSION)\"" > src/version.ml

announce:
	@ echo "Source configuration ..."

configure: announce ledit version
