# -*- makefile-gmake -*-

###########################
## Package configuration ##
###########################
.PHONY: all

all: all-generic

STUDENTS  = $(shell cat AUTEURS | tr '\n' ',' | cut -d, -f1,4 | tr ',' '-')

VERSION	  = 16.2
TARGET	  = flap
TARGETEXT = flap
PACKAGE	  = flap-$(STUDENTS)-$(VERSION)

